networks:
  lgtm-network:
    driver: bridge

services:
  # --- Tracing Backend ---
  minio:
    image: minio/minio:latest
    entrypoint: ["sh", "-c", "mkdir -p /data/tempo-bucket && /usr/bin/docker-entrypoint.sh server /data --console-address ':9001'"]
    environment:
      - MINIO_ROOT_USER=tempo_user
      - MINIO_ROOT_PASSWORD=tempo_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    networks:
      - lgtm-network

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # HTTP
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - minio
    networks:
      - lgtm-network

  # --- Logging Backend ---
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - lgtm-network

  # --- Log Collector ---
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Read access to Docker logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - lgtm-network
    depends_on:
      - loki

  # --- Visualization ---
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - tempo
      - loki
    networks:
      - lgtm-network