global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'parser-dev'
    static_configs:
      - targets: [ '10.20.20.230:5000' ]
  - job_name: 'parser-prod'
    static_configs:
      - targets: [ '10.20.100.230:5000' ]
  - job_name: node
    scrape_interval: 1m
    scrape_timeout: 55s
    static_configs:
      - targets: ['mbit-de-main:9100']
