apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebot
  labels:
    app: homebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebot
  template:
    metadata:
      labels:
        app: homebot
    spec:
      containers:
      - name: homebot
        image: akhaladze/iot-homebot:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-storage
          mountPath: /app/data # Путь, где лежат ваши .db и .parquet файлы
      volumes:
      - name: data-storage
        hostPath:
          path: /opt/homebot/data # Папка на вашем сервере (nuc или gluck2)
---
apiVersion: v1
kind: Service
metadata:
  name: homebot-service
spec:
  selector:
    app: homebot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebot-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: homebot.cloudpak.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homebot-service
            port:
              number: 80
