global:
  smtp_from: 'alerts@example.com'
  smtp_smarthost: 'smtp.example.org:587'
  smtp_auth_username: 'user'
  smtp_auth_password: 'password'
  resolve_timeout: '5m'

route:
  receiver: 'default'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [service_name, alertname]

receivers:
  - name: 'default'
    email_configs:
      - to: 'oncall@example.com'
        send_resolved: true
