storage-path: "/var/lib/pyroscope"

retention: 48h
exemplars-retention: 24h

# scrape-configs:
#  job-name: pyroscope
#  scrape-interval: 10s
#  enabled-profiles: [cpu, mem]

server:
  http_address: "0.0.0.0:4040"

scrape_configs:
  - job_name: "alloy"
    static_configs:
      - targets: ["10.20.20.44:12345"]
    profiling_config:
      pprof_config:
        profile_path: "/debug/pprof/profile"
        delta: false
  - job-name: pyroscope 
    scrape-interval: 10s
    enabled-profiles: [cpu, mem]

